---
- name: UFW - Set default incoming policy to deny
  community.general.ufw:
    direction: incoming
    policy: deny
  tags: ufw_rules

- name: UFW - Set default outgoing policy to allow
  community.general.ufw:
    direction: outgoing
    policy: allow
  tags: ufw_rules

- name: UFW - Allow SSH
  community.general.ufw:
    rule: allow
    port: 2275
    proto: tcp
  tags: ufw_rules

- name: UFW - Allow HTTP Server
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp
  tags: ufw_rules

- name: UFW - Allow HTTPS Server
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp
  tags: ufw_rules

- name: UFW - Enable UFW
  community.general.ufw:
    state: enabled
    logging: "on" # Optional, enable logging
  tags: ufw_rules
